library("sqldf");
temp <- tempfile();
fileURL <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip";
targetFile <- "household_power_consumption.txt";
download.file(fileURL, temp);
unz(temp, "household_power_consumption.txt");
dataset <- read.csv.sql(targetFile, sql="SELECT * from file where Date = '1/2/2007' or Date = '2/2/2007'", header = TRUE, sep = ";");
unlink(temp);
dataset$DateTime <- paste(dataset$Date, dataset$Time);
dataset$DateTime <- strptime(dataset$DateTime, "%d/%m/%Y %H:%M:%S");                      
png(filename="plot2.png",width=480,height=480,units="px");
plot(dataset$DateTime,dataset[,3], type="l", xlab="",ylab="Global Active Power (kilowatts)");
dev.off();
